import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
// import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// export const metadata = {
// 	title: "Yomify",
// 	description:
// 		"Build Interactive wedding invitations, company profiles, and life documentation with ease.",
// 	metadataBase: new URL("https://www.yomify.com"),
// 	openGraph: {
// 		type: "website",
// 		url: "https://www.yomify.com/",
// 		title: "Yomify",
// 		description:
// 			"Build Interactive wedding invitations, company profiles, and life documentation with ease.",
// 		images: [
// 			{
// 				url: "/meta.webp",
// 				width: 1200,
// 				height: 630,
// 			},
// 		],
// 	},
// 	twitter: {
// 		card: "summary_large_image",
// 		title: "Yomify",
// 		description:
// 			"Build Interactive wedding invitations, company profiles, and life documentation with ease.",
// 		images: ["/meta.webp"],
// 	},
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
				<Toaster position="top" />
				{/* <GoogleAnalytics gaId="G-920REJG2GY" /> */}
			</body>
		</html>
	);
}
